config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'auth/vkontakte/callback', to: 'omniauth#create'

  resources :users do
    resources :profiles, only: [:edit, :update]
    get :change_permission, on: :member
  end

  resources :posts do
    get :favourite, on: :member
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
    get :login_with, on: :member
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/favourite_post.rb
class FavouritePost < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  def self.manage(post)
    object = find_by(post: post)
    object ? object.destroy : create(post: post)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title, :desciption, presence: true

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  has_one  :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :accounts, dependent: :destroy
  has_many :favourite_posts, dependent: :destroy
  before_save :encrypt_password
  validates_presence_of :email
  # validates_uniqueness_of :email
  validates_confirmation_of :password
  validates_presence_of :password, on: :create

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    end
  end

  def encrypt_password
    return if password.blank?
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
  before_action :current_resources

  def create
    if @user
      @account[user: @user]
    else
      @user = @account.create_user(vk_params)
    end
    @account.save
    session[:user_id] = @user.id
    redirect_to new_post_path
  end

  private

  def current_resources
    @account = Account.find_or_create_by(uid: auth_hash[:uid],
                                         provider: auth_hash[:provider],
                                         email: auth_hash[:email])
    @user = User.find_by(email: auth_hash[:info][:email])
  end

  def vk_params
    password = "#{rand(100)}_sample_password_#{rand(100)}"
    {
      email: auth_hash[:info][:email],
      remote_avatar_url: auth_hash[:extra][:raw_info][:photo_200],
      password: password,
      password_confirmation: password
    }
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :favourite]
  before_action :require_user

  def index
    @posts = Post.all
    render :index
  end

  def show
    @post.increment!(:page_views)
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Пост успешно создан.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Пост успешно обновлен.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Пост успешно удалено.' }
    end
  end

  def favourite
    current_user.favourite_posts.manage(@post)
  end

  private

  def require_user
    redirect_to root_path unless current_user
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :desciption, :image)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :current_profile, only: [:edit, :update]
  def edit
    @user = User.find(params[:user_id])
  end

  def update
   
    if @profile.update(profile_params)
      flash[:success] = 'Profile updated'
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def current_profile
     @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :location, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to new_post_path, notice: :Logged_in!
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def login_with
    session[:user_id] = params[:id]
    redirect_to new_post_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: :Logged_out!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :change_permission]
  before_action :require_user, except: [:new, :create]

  def index
    @users = User.order(:email)
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @profile = @user.create_profile
      redirect_to edit_user_profile_path(@user.id, @profile.id)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
  end

  def change_permission
    @user.update(admin: !@user.admin)
    redirect_to :back
  end

  private

  def require_user
    redirect_to root_path unless current_user
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
#
module PostsHelper
  def favourite_post(post)
    if current_user.favourite_posts.map(&:post).include?(post)
      'text-success'
    else
      'text-muted'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset=”utf-8”>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <%= render 'shared/header' %>
  <div class="container">
    <%= yield %>
  </div>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :desciption %><br>
    <%= f.text_area :desciption %>
  </p>
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
  <div class="actions"><%= f.submit "Create post", :class => "button" %></div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= render 'form' %>

app/views/posts/favourite.js.erb
$('#post_<%= @post.id %>').toggleClass('text-success').toggleClass('text-muted');

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>List of posts</h1>
<table class="table table-striped">
  <% @posts.each do |post| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td class="list">
        <dt>Email</dt>
        <dt>Title</dt>
        <dt>Desciption</dt>
      </td>
      <td class="list_description">
        <dt><%= post.user.email %></dt>
        <dt><%= post.title %></dt>
        <dt><%= post.desciption %></dt>
      </td>
      <td><%= link_to favourite_post_path(post), id: "post_#{post.id}", class: favourite_post(post), remote: true do %>
        <i class="glyphicon glyphicon-heart"></i>
        <% end %>
      </td>
      <td class="list_actions">
        <%= link_to 'Show', post, class: "label label-info" %><br/>
        <% if current_user == post.user %>
          <%= link_to 'Edit', edit_post_path(post), class: "label label-primary" %> |
          <%= link_to 'Delete', post, class: "label label-warning", method: :delete,data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<form class="form-horizontal">
  <p>
    <%= @post.page_views %>
  </p>
  <div class="field">
    <%= label_tag :title %>
    <%= @post.title %>
  </div>
  <div class="field">
    <%= label_tag :desciption %>
    <%= @post.desciption %>
  </div>
  <p>
    <%= image_tag @post.image.url %>
  </p>
</div>
<% if current_user == @post.user %>
  <%= link_to 'Edit', edit_post_path(@post), class: "label label-primary" %> |
<% end %>

app/views/profiles/edit.html.erb
<h1>Profile</h1>
<div id="page_wrapper">
<%= form_for([@user, @profile]) do |f| %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.file_field :avatar %>
  </p>

  <div class="actions"><%= f.submit "Update profile", class: "button" %></div>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-default">
  <div class="container" class="col-lg-6">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div> 
    <div class="collapse navbar-collapse" id="menu" >
      <ul class="nav navbar-nav" >
        <% if current_user.try(:admin?) %>
          <li><%= link_to "User list", users_path, method: "get" %></li>
        <% end %>
        <% if current_user %>
          <li ><%= link_to "New post", new_post_path, method: "get" %></li>
          <li><%= link_to "List of posts", posts_path, method: "get" %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <a class="navbar-brand" href="#"><%= current_user[:email] %></a>
          <li><%= link_to "Profile", edit_user_profile_path(current_user, current_user.profile) %></li>
          <li><%= link_to "Exit", sessions_path , method: :delete%></li>
        <% else %>
          <li><%= link_to "auth/vkontakte" do%>
            <i class = "fa fa-vk fa-2x"></i>
            <i class="glyphicon glyphicon-btc"></i>
          <% end %>
          </li>
          <li><%= link_to "Registration", new_user_path, method: "get" %></li>
          <li><%= link_to "Log in", new_session_path, method: "get" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="blog_form">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-horizontal">
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %>:
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Create user", :class => "button" %></div>
<% end %>
</div>

app/views/users/destroy.js.erb
$('#user_<%= @user.id %>').remove();

app/views/users/edit.html.erb
<p>Edit user</p>
<%= render 'form' %>

app/views/users/index.html.erb
<h3>Users list</h3>
<table class="table table-striped">
  <tr>
    <td>№</td>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th>Status</th>
  </tr>
  <tbody>
  <% @users.each  do |user| %>
    <tr id = <%= "user_#{user.id}" %> >
      <td><%=user.id%></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Edit', edit_user_path(user), class: "label label-primary" %></td>
      <td><%= link_to 'Log in', login_with_session_path(user.id), class: "label label-info" %></td>
      <% if user.admin %>
        <td><%= link_to 'Admin', change_permission_user_path(user), class: "label label-success"%></td>
      <% else %>
        <td><%= link_to 'User', change_permission_user_path(user), class: "label label-warning" %></td>
      <% end %>
      <% unless current_user.email == user.email %>
        <td><%= link_to 'Delete', user, class: "label label-danger", method: :delete, remote: true %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h3>New User</h3>
<%= render 'form' %>